import type { NextPage } from 'next'
import Head from 'next/head'
import { 
  ModalCloseButton,
  FormErrorMessage,
  useDisclosure,
  ModalOverlay,
  ModalContent,
  FormControl,
  ModalHeader,
  ModalFooter,
  ModalBody,
  Heading,
  Button,
  chakra,
  Input,
  Image,
  Modal,
  Flex,
  Box,
  FormLabel,
  Textarea,
} from '@chakra-ui/react'
import { useForm } from "react-hook-form";

const Home: NextPage = () => {
  const { isOpen, onOpen, onClose } = useDisclosure()
  const {
    handleSubmit,
    register,
    formState: { errors, isSubmitting },
    reset
  } = useForm()

  const onSubmit: any = (values: any) => {
    console.log(values);
  }

  return (
    <Box height='100vh'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        flexDir={'column'}
        justifyContent='space-between'
        h='100%'
      >
        <Flex
          h='20vh'
          alignItems={'center'}
          justifyContent='center'
        >
          <Image
            boxSize='2xs'
            objectFit='contain'
            src="/genrae-logo-300x72.png"
          />
        </Flex>
        <Flex
          minH='60vh'
          flexDir='column'
          justifyContent={'center'}
          alignItems='center'
        >
          <Image
            boxSize='3xl'
            objectFit='contain'
            objectPosition='center center'
            src="/Genrae-Astronaut-1024x954.jpg"
          />
        </Flex>
        <Flex
          h='20vh'
          flexDir={'column'} alignItems='center'
        >
          <Heading
            fontSize='36px'
            marginBottom="32px"
          >
            Coming 2023
          </Heading>
          <Button
            variant={'outline'}
            width='185px'
            borderWidth='2px'
            h='48px'
            fontSize='18px'
            borderRadius='50px'
            fontStyle='italic'
            onClick={onOpen}
          >
            Join Us
          </Button>
        </Flex>
      </Flex>
      <Modal isOpen={isOpen} onClose={onClose}>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader>Leave More About Flow</ModalHeader>
          <ModalCloseButton />
          <ModalBody>
            <chakra.form
              onSubmit={handleSubmit(onSubmit)}
            >
              <FormControl
                isInvalid={errors.email}
              >
                <FormLabel htmlFor="email">Email:</FormLabel>
                <Input
                  id='email'
                  {...register('email', {
                    required: 'Please provide an email'
                  })} />
                  <FormErrorMessage>
                    { errors.email && errors.email.message }
                  </FormErrorMessage>
              </FormControl>
              <FormControl>
                <FormLabel
                  htmlFor="notes"
                >
                  Notes:
                </FormLabel>
                <Textarea
                  id='notes'
                  {...register('notes')}
                ></Textarea>
                <FormErrorMessage>
                  { errors.notes && errors.notes.message }
                </FormErrorMessage>
              </FormControl>
            </chakra.form>
          </ModalBody>
          <ModalFooter>
            <Button
              type='submit'
              colorScheme='blue'
              mr={3}
              onClick={onClose}
              isLoading={isSubmitting}
            >
              Sign Up
            </Button>
          </ModalFooter>
        </ModalContent>
      </Modal>

    </Box>
  )
}

export default Home
