import type { NextPage } from 'next'
import Head from 'next/head'
import {
  ModalCloseButton,
  FormErrorMessage,
  useDisclosure,
  ModalOverlay,
  ModalContent,
  FormControl,
  ModalHeader,
  ModalFooter,
  ModalBody,
  FormLabel,
  Textarea,
  Heading,
  Button,
  chakra,
  Input,
  Image,
  Modal,
  Flex,
  Box,
  InputRightElement,
  InputRightAddon,
  InputGroup,
  InputLeftElement,
  InputLeftAddon,
} from '@chakra-ui/react'
import { useForm, Resolver } from "react-hook-form";

type EmailList = {
  email: string;
}

const resolver: Resolver<EmailList> = async (values) => {
  return {
    values: values.email ? values : {},
    errors: !values.email
      ? {
        email: {
          type: 'required',
          message: 'Email is required'
        },
      } : {},
  };
}

const Home: NextPage = () => {
  const { isOpen, onOpen, onClose } = useDisclosure()
  const {
    handleSubmit,
    register,
    formState: { errors, isSubmitting },
    reset
  } = useForm<EmailList>({ resolver });

  const onSubmit: any = handleSubmit((data) => console.log(data));

  return (
    <Box height='100vh'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        flexDir={'column'}
        h='100%'
      >
        <Flex
          mt='64px'
          alignItems={'center'}
          justifyContent='center'
          flexDir='column'
        >
          <Image
            boxSize='2xs'
            h='60px'
            objectFit='contain'
            src="/genrae-logo-300x72.png"
          />
        </Flex>
        <Flex
          flexDir='column'
          justifyContent={'center'}
          alignItems='center'
          flexGrow={0}
          mb='-48px'
        >
          <Image
            w='80%'
            src="/Astronaut-Centered.png"
          />
        </Flex>
        <Flex
          flexDir={'column'}
          alignItems='center'
        >
          <Heading
            color='#070707'
            fontSize="90px"
            lineHeight={'90px'}
            fontFamily='Manrope'
            fontWeight={'bold'}
            width='445px'
            mb='32px'
            textAlign='center'
          >Own the difference.</Heading>
          <Heading
            fontSize='24px'
            marginBottom="32px"
            fontFamily={'work sans'}
            color='#070707'
          >
            The future of home buying is coming soon.
          </Heading>
          <chakra.form
            onSubmit={onSubmit}
            display='flex'
            alignItems='center'
          >
            <FormControl
              isInvalid={errors?.email ? true : false}
            >
              <InputGroup w='32em'>
                <Input
                  h='64px'
                  border='2px'
                  id='email'
                  {...register('email')}
                  placeholder='Enter email address'
                  fontSize='21px'
                  fontFamily={'work sans'}
                  fontWeight='medium'
                  borderRadius={28}
                />
                <InputRightElement
                  w='fit-content'
                  h='100%'
                  right={0}
                >
                  <Button
                    borderRadius={28}
                    h='inherit'
                    bg='#070707'
                    px='32px'
                    type='submit'
                    colorScheme='blue'
                    onClick={onClose}
                    isLoading={isSubmitting}
                    fontFamily={'work sans'}
                    fontWeight='medium'
                    fontSize={'21px'}
                  >
                    Get Early Access
                  </Button>
                </InputRightElement>
              </InputGroup>
              <FormErrorMessage>
                {errors.email && errors.email.message}
              </FormErrorMessage>
            </FormControl>
          </chakra.form>
        </Flex>
      </Flex>
    </Box>
  )
}

export default Home
